# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Seenema CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'seenema-frontend/package-lock.json'
      - name: Install package dependencies
        working-directory: seenema-frontend
        run: npm install --legacy-peer-deps
      - name: Build frontend
        working-directory: seenema-frontend
        run: npm run build --if-present
      - name: Test frontend
        working-directory: seenema-frontend
        run: npm test

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build
          build-root-directory: seenema-backend
          cache-disabled: true
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: test
          build-root-directory: seenema-backend
